name: 'Terraform Apply'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  issues: write

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > application_default_credentials.json

    - name: Create sensitive.auto.tfvars
      run: |
        cat > sensitive.auto.tfvars <<EOL
        gcp_project                        = "${{ secrets.GCP_PROJECT }}"
        gcp_project_region                 = "${{ secrets.GCP_REGION }}"
        gcp_project_zone                   = "${{ secrets.GCP_ZONE }}"
        gcp_billing_project                = "${{ secrets.GCP_BILLING_PROJECT }}"
        gcp_billing_account_name           = "${{ secrets.GCP_BILLING_ACCOUNT_NAME }}"
        gcp_billing_alert_currency_code    = "${{ vars.GCP_BILLING_CURRENCY }}"
        gcp_billing_alert_amount           = "${{ vars.GCP_BILLING_AMOUNT }}"
        access_credentials                 = "./application_default_credentials.json"
        cloudflare_api_token               = "${{ secrets.CLOUDFLARE_API_TOKEN }}"
        actual_subdomain                   = "${{ vars.ACTUAL_SUBDOMAIN }}"
        actual_server_image_version_tag    = "${{ vars.ACTUAL_SERVER_VERSION }}"
        actual_tasks_image_version_tag     = "${{ vars.ACTUAL_TASKS_VERSION }}"
        actual_auto_sync_image_version_tag = "${{ vars.ACTUAL_AUTO_SYNC_VERSION }}"
        actual_tasks_config = {
          cron_expression = "${{ vars.ACTUAL_TASKS_CRON }}"
          actual = {
            server_url      = "${{ vars.ACTUAL_SERVER_URL }}"
            server_password = "${{ secrets.ACTUAL_SERVER_PASSWORD }}"
            sync_id         = "${{ secrets.ACTUAL_SYNC_ID }}"
            file_password   = "${{ secrets.ACTUAL_FILE_PASSWORD }}"
          }
          features = {
            payee_rename = {
              is_enabled  = true
              regex_match = "${{ vars.ACTUAL_PAYEE_REGEX }}"
            }
            interest_calculation = {
              is_enabled         = false
              rate               = ""
              payee_id           = ""     
              main_account_id    = ""
              mortage_account_id = ""
            }
            ghostfolio = {
              is_enabled     = false
              account        = ""
              actual_account = ""
              payee_name     = ""
              server_url     = ""
              token          = ""
            }
            hold_income_for_next_month = {
              is_enabled = false
            }
            bank_sync = {
              is_enabled = false
            }
          }
        }
        actual_auto_sync_config = {
          server_url      = "${{ vars.ACTUAL_SERVER_URL }}"
          server_password = "${{ secrets.ACTUAL_SERVER_PASSWORD }}"
          sync_ids        = "${{ secrets.ACTUAL_SYNC_ID }}"
          file_passwords  = "${{ secrets.ACTUAL_FILE_PASSWORD }}"
          cron_schedule   = "${{ vars.ACTUAL_AUTO_SYNC_CRON }}"
          log_level       = "info"
          run_on_start    = true
        }
        mealie_subdomain         = "${{ vars.MEALIE_SUBDOMAIN }}"
        mealie_image_version_tag = "${{ vars.MEALIE_VERSION }}"
        mealie_config = {
          timezone = "${{ vars.MEALIE_TIME_ZONE }}"
        }
        EOL

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Wait for approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: Joaodss
        timeout-minutes: 60

    - name: Terraform Apply
      run: terraform apply tfplan
