name: 'Terraform Apply'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > application_default_credentials.json

    - name: Create sensitive.auto.tfvars
      run: |
        cat > sensitive.auto.tfvars <<EOL
        gcp_project                     = "${{ secrets.GCP_PROJECT }}"
        gcp_project_region              = "${{ secrets.GCP_REGION }}"
        gcp_project_zone                = "${{ secrets.GCP_ZONE }}"
        gcp_billing_project             = "${{ secrets.GCP_BILLING_PROJECT }}"
        gcp_billing_account_name        = "${{ secrets.GCP_BILLING_ACCOUNT_NAME }}"
        gcp_billing_alert_currency_code = "${{ vars.GCP_BILLING_CURRENCY }}"
        gcp_billing_alert_amount        = "${{ vars.GCP_BILLING_AMOUNT }}"
        access_credentials              = "./application_default_credentials.json"
        cloudflare_api_token            = "${{ secrets.CLOUDFLARE_API_TOKEN }}"
        actual_subdomain                = "${{ vars.ACTUAL_SUBDOMAIN }}"
        actual_server_image_version_tag = "${{ vars.ACTUAL_SERVER_VERSION }}"
        EOL

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Wait for approval
      uses: trstringer/manual-approval@v1
      with:
        minimum-approvals: 1
        timeout-minutes: 60

    - name: Terraform Apply
      run: terraform apply tfplan
